services:
  - type: web
    name: bargainbuddy
    env: static
    buildCommand: bash build.sh
    staticPublishPath: dist
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SKIP_INSTALL_DEPS
        value: "true"
